name: Test

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: install dependencies
      run: sudo apt update && sudo apt install -y libglfw3-dev libgles-dev libfreetype-dev libutf8proc-dev nlohmann-json3-dev catch2 clang
    - name: compile terminal
      run: cd entry/src/main/cpp && clang++ -std=c++17 terminal.cpp -I/usr/include/freetype2 -DSTANDALONE -lGLESv2 -lglfw -lfreetype -lutf8proc -o terminal
    - name: compile test
      run: cd entry/src/main/cpp && clang++ -std=c++17 -O2 -fsanitize=address test.cpp terminal.cpp -I/usr/include/freetype2 -DSTANDALONE -DTESTING -o test -lGLESv2 -lglfw -lfreetype -lutf8proc -lCatch2Main -lCatch2
    - name: run test
      run: cd entry/src/main/cpp && ./test
